
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label lblURLs;
	private global::Gtk.TextView txtURLs;
	private global::Gtk.Button btnStart;
	private global::Gtk.Button btnClear;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView tvResults;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Website Checker");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-question", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(4));
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblURLs = new global::Gtk.Label ();
		this.lblURLs.Name = "lblURLs";
		this.lblURLs.LabelProp = global::Mono.Unix.Catalog.GetString ("URLs");
		this.hbox1.Add (this.lblURLs);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblURLs]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtURLs = new global::Gtk.TextView ();
		this.txtURLs.CanFocus = true;
		this.txtURLs.Name = "txtURLs";
		this.hbox1.Add (this.txtURLs);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtURLs]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnStart = new global::Gtk.Button ();
		this.btnStart.CanFocus = true;
		this.btnStart.Name = "btnStart";
		this.btnStart.UseUnderline = true;
		// Container child btnStart.Gtk.Container+ContainerChild
		global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w4 = new global::Gtk.HBox ();
		w4.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w5 = new global::Gtk.Image ();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
		w4.Add (w5);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
		w7.UseUnderline = true;
		w4.Add (w7);
		w3.Add (w4);
		this.btnStart.Add (w3);
		this.hbox1.Add (this.btnStart);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnStart]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnClear = new global::Gtk.Button ();
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		// Container child btnClear.Gtk.Container+ContainerChild
		global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w13 = new global::Gtk.HBox ();
		w13.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w14 = new global::Gtk.Image ();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
		w13.Add (w14);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w16 = new global::Gtk.Label ();
		w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Clear");
		w16.UseUnderline = true;
		w13.Add (w16);
		w12.Add (w13);
		this.btnClear.Add (w12);
		this.hbox1.Add (this.btnClear);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnClear]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvResults = new global::Gtk.TreeView ();
		this.tvResults.CanFocus = true;
		this.tvResults.Name = "tvResults";
		this.GtkScrolledWindow.Add (this.tvResults);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w23.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnStart.Clicked += new global::System.EventHandler (this.OnBtnStartClicked);
		this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
	}
}
