
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label lblURLs;
	private global::Gtk.TextView txtURLs;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Button btnStart;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView tvResults;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(4));
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblURLs = new global::Gtk.Label ();
		this.lblURLs.Name = "lblURLs";
		this.lblURLs.LabelProp = global::Mono.Unix.Catalog.GetString ("URLs");
		this.hbox1.Add (this.lblURLs);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblURLs]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtURLs = new global::Gtk.TextView ();
		this.txtURLs.CanFocus = true;
		this.txtURLs.Name = "txtURLs";
		this.hbox1.Add (this.txtURLs);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtURLs]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnStart = new global::Gtk.Button ();
		this.btnStart.CanFocus = true;
		this.btnStart.Name = "btnStart";
		this.btnStart.UseUnderline = true;
		// Container child btnStart.Gtk.Container+ContainerChild
		global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w4 = new global::Gtk.HBox ();
		w4.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w5 = new global::Gtk.Image ();
		w4.Add (w5);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
		w7.UseUnderline = true;
		w4.Add (w7);
		w3.Add (w4);
		this.btnStart.Add (w3);
		this.fixed2.Add (this.btnStart);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnStart]));
		w11.X = 94;
		w11.Y = 11;
		this.hbox1.Add (this.fixed2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed2]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvResults = new global::Gtk.TreeView ();
		this.tvResults.CanFocus = true;
		this.tvResults.Name = "tvResults";
		this.GtkScrolledWindow.Add (this.tvResults);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w15.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnStart.Clicked += new global::System.EventHandler (this.OnBtnStartClicked);
	}
}
